function  Impl_TrainCNN_LABCH(pathDB, file, epoch, dirOut, nameOut, colorSpace)
dbPopulations = dir(strcat(pathDB,file)); % Load data
N = length(dbPopulations);
finalDir = strcat(pathDB, dirOut); % Create directory
if ~exist('',finalDir)
    mkdir(finalDir);
end

if strcmp(colorSpace, 'LCH')==1
    [ XTrainLCH, YTrainLCH, XTrainPop, XTrainColor, ...
        XValidationLCH, YValidationLCH, XValidationPop, XValidationColor, ...
        XTestLCH, YTestLCH, XTestPop, XTestColor]...
        = Load3H2DLCH(dbPopulations, pathDB);
    TrainCNNWith3H2DLABCH(XTrainLCH, YTrainLCH, XTrainPop, XTrainColor, ...
        XValidationLCH, YValidationLCH, XValidationPop, XValidationColor, ...
        XTestLCH, YTestLCH, XTestPop, XTestColor, epoch, pathDB, dirOut, nameOut);
end
if strcmp(colorSpace, 'LAB')==1 %Cie lab
    [ XTrainLAB, YTrainLAB, XTrainPop, XTrainColor, ...
        XValidationLAB, YValidationLAB, XValidationPop, XValidationColor, ...
        XTestLAB, YTestLAB, XTestPop, XTestColor]...
        = Load3H2DLAB(dbPopulations, pathDB, 3);
    TrainCNNWith3H2DLAB(XTrainLAB, ...
        YTrainLAB, XTrainPop, XTrainColor, XValidationLAB, YValidationLAB, ...
        XValidationPop, XValidationColor, XTestLAB, YTestLAB, XTestPop, XTestColor, epoch, pathDB, dirOut, nameOut)
end

end