function  Impl_TrainCNNCurve(pathDB, file, epoch, dirOut, nameOut, colorSpace, channels)
    dbPopulations = dir(strcat(pathDB,file)); % Load data
    N = length(dbPopulations);   
    finalDir = strcat(pathDB, dirOut); % Create directory
    if ~exist('',finalDir)
        mkdir(finalDir);
    end

    if strcmp(colorSpace, 'HSI')==1
        [ XTrainHSI, YTrainHSI, XTrainPop, XTrainColor, ...
            XValidationHSI, YValidationHSI, XValidationPop, XValidationColor, ...
            XTestHSI, YTestHSI, XTestPop, XTestColor]...
            = Load3H2DHSI(dbPopulations, pathDB, channels);
        if channels == 1
            TrainCNNWith1H2DHSICurve(XTrainHSI, YTrainHSI, XTrainPop, XTrainColor, ...
                XValidationHSI, YValidationHSI, XValidationPop, XValidationColor, ...
                XTestHSI, YTestHSI, XTestPop, XTestColor, epoch, pathDB, dirOut, nameOut);
        else %3 channels
            TrainCNNWith3H2DHSICurve(XTrainHSI, YTrainHSI, XTrainPop, XTrainColor, ...
                XValidationHSI, YValidationHSI, XValidationPop, XValidationColor, ...
                XTestHSI, YTestHSI, XTestPop, XTestColor, epoch, pathDB, dirOut, nameOut);
        end

    end
    if strcmp(colorSpace, 'LAB')==1
        [ XTrainLAB, YTrainLAB, XTrainPop, XTrainColor, ...
            XValidationLAB, YValidationLAB, XValidationPop, XValidationColor, ...
            XTestLAB, YTestLAB, XTestPop, XTestColor]...
            = Load3H2DLAB(dbPopulations, pathDB, channels);
        if channels == 1

            TrainCNNWith1H2DLABCurve(XTrainLAB, ...
                YTrainLAB, XTrainPop, XTrainColor, XValidationLAB, YValidationLAB, ...
                XValidationPop, XValidationColor, XTestLAB, YTestLAB, XTestPop, XTestColor, epoch, pathDB, dirOut, nameOut)
        else %3 channels
            TrainCNNWith3H2DLABCurve(XTrainLAB, ...
                YTrainLAB, XTrainPop, XTrainColor, XValidationLAB, YValidationLAB, ...
                XValidationPop, XValidationColor, XTestLAB, YTestLAB, XTestPop, XTestColor, epoch, pathDB, dirOut, nameOut)

        end

    end

end